### ISSUE TITLE
Energy increasing with bond dimension

### ISSUE THREAD

**Issue by Gertian** [maartenvd/MPSKit.jl#107]
I'm running some GS searches for a model with 4 site unit cell and find an increasing energy as the bond dimension increases.

The context in which the 4 site unit cell arises should be irrelevant, but for completeness, it's a lattice model defined on a thin (2 site wide) strip which has unit cell of 2 in the extended direction. After snaking this becomes an effective linear model with unit cell 4.

Furthermore this behavior seems to be independent of the algorithm used to find the GS. Finally, the high D results seem to converge (from below) to some value that is not correct (I can analytically obtain the GS energy for certain parameters).

Has anyone experienced similar behavior and found a way out ?

**Comment by lkdvos** [comment]
I have not yet experienced this, but it is a bit hard to guess what's going on with the limited amount of information. Depending on lots of different scenarios, here are some things I can think of off the top of my head:
* Have you checked that your higher bond dimension cases are fully converged? If the tolerances are not small enough, I could imagine that the error measure might not be a bond-dimension independent measure for convergence, and thus you could just be further from the lowest energy state within the manifold of that bond dimension. Maybe the variance can give you an idea for this.
* There could be some weird interplay with how the environments scale their tolerances based on the current error measure. This could cause some non-variational behaviour
* It might be the case that you are incorrectly selecting your sectors/growing your sectors. What I mean by this is that for example, if you would have a groundstate in SU2 that has `SU2Space(0 => 10, 1 => 5, 2 => 1, ...)`, but initialize the virtual space as `SU2Space(0 => 1, 1 => 10, 2 => 20)`, often the algorithm can get stuck in local minima-like things.

Maybe we can discuss a bit more what you are encountering if it is not possible to easily share your results here.

**Comment by Gertian** [comment]
@lkdvos, thanks for these insights. 

I turns out our Hamiltonian had some mistake in it which caused the weird behavior. I've now re-implemented the Hamiltonian and get more reasonable outcomes...

If you want I could try to isolate a M(not)WE which might provide an interesting testcase ?

**Comment by lkdvos** [comment]
That depends, if your Hamiltonian wasn't fully Hermitian, I guess all of the above does not really matter anyways? I am not sure if it's something we can really test against if we don't know what's causing the behaviour :grin:

**Comment by Gertian** [comment]
@lkdvos Ok we finally figured out what was wrong.
Due to a wrong convention, the GS of the Hamiltonian had an infinitely large unit cell which explains all the weird observed behaviors.

Now MPSKit seems to be performing well (as expected :) )
