### ISSUE TITLE
gauge flag

### ISSUE THREAD

**Issue by maartenvd** [maartenvd/MPSKit.jl#2]
finite states should include information on how they were gauged, because now time evolution algorithms assume right orthogonalized states which may be incorrect.

**Comment by Jutho** [comment]
Hi Maarten, I have some code for that, which I might add and combine with your code.

**Comment by maartenvd** [comment]
That would be great!

**Comment by Jutho** [comment]
Ok I'll start preparing a PR this afternoon.
