### ISSUE TITLE
MPO without translation symmetry?

### ISSUE THREAD

**Issue by huangrzh** [maartenvd/MPSKit.jl#20]
Hi, I notice the MPO in MPSKit currently only supports single-site unit-cell models. Is it possible to construct MPOs with a 2-site unit cell? For example, there are different odd and even bond interactions in a Hamiltonian or finite width ladder systems. Thanks.

**Comment by maartenvd** [comment]
Yes it does! The InfiniteMPO type is a vector of mpo tensors, and they repeat periodically. So you can do a 2-site unit cells (and you can even do n x m unit cells). This infiniteMPO operator represents a partition function, so it's only used for stat-mech.

You appear to be asking about quantum hamiltonians, they're represented as "MPOHamiltonians". The difference between InfiniteMPO is that we keep track of the sparseness - an mpo representation of a hamiltonian is mostly zero. Also mpohamiltonians are defined as something repeating periodically with some unit cell.

While not the most readable code, this for example implements the harper hofstatder model on a cylinder or strip (depening on periodic being true or false) https://github.com/maartenvd/MPSKitModels.jl/blob/master/src/hofstadter.jl

**Comment by huangrzh** [comment]
Sorry for the misunderstanding. MPSKit can use multisite MPOs and thanks for the example.
