### ISSUE TITLE
A possible bug in finitemps.jl?

### ISSUE THREAD

**Issue by huangrzh** [maartenvd/MPSKit.jl#22]
At line 105 in the finitemps.jl, I think the following code might cause some unexpected result:
(site_tensors[i],C) = leftorth!(site_tensors[i],alg=QRpos());

I think after the operation for i=1, all the other tensors are changed at the same time, which should not so. For example, consider this example:

d = 4; N = 2
hd = Int(sqrt(d))
Id = Matrix(1.0*I,hd,hd)/sqrt(2)
Id = reshape(Id, (1, d, 1))
site_tensors = [TensorMap(Id, ℝ^1 ⊗ ℝ^d, ℝ^1) for n=1:N]

i = 1
(site_tensors[i],C) = leftorth!(site_tensors[i],alg=QRpos()); normalize!(C);

In this example, site_tensors[2] is also changed!  I think leftorth should replace leftorth! . Also, there may exist similar situations in other places in this package.

**Comment by maartenvd** [comment]
that is a great point! It should be fixed by https://github.com/maartenvd/MPSKit.jl/commit/c93518212c40b3b0da7e48de55da898ac610ed69

**Comment by huangrzh** [comment]
@maartenvd Yes, now the codes should be fine.
