### ISSUE TITLE
writing and loading MPS into files? 

### ISSUE THREAD

**Issue by huangrzh** [maartenvd/MPSKit.jl#31]
I am wondering whether it is possible to write all the AL,AR,CR,AC tensors and even the environment tensors of a MPS (sometimes the unit cell can be large) into a single file? As MPSKit relies on TensorKit, I think one has to store each TensorMap into an independent file for now, which is not convenient sometimes. So is there a simple way to realize it?

**Comment by Jutho** [comment]
`TensorMap` objects can easily be converted into a `Dict`, which is the most flexible way of storing them. Maybe MPSKit could do something similar by defining conversions to and from `Dict`?

**Comment by maartenvd** [comment]
I'm certainly ok with implementing something like this, so far I've always used JLD2, which works out of the box for mpskit and tensorkit objects.

**Comment by huangrzh** [comment]
Yes, TensorMap can be easily converted into a Dict and then written into a file. Just wondering is there a way to write a vector (or maybe an array) of several Dict objects into a single file? I didn't find a simple solution.

**Comment by Jutho** [comment]
I think it would be beneficial to convert an MPS to a nested dict, if at least there are various packages that support writing vectors of dicts, or nested dicts of dicts.

However, it seems @huangrzh  's issue (if I understood correctly) is saving a vector of dicts into a single file, which is not really an MPSKit issue?

**Comment by Jutho** [comment]
One issue that I just encountered is that simply saving an MPS with JLD(2), is that it stores all of the `AL`, `AR`, `AC` and `C` matrices (this was a `FiniteMPS`) and so the file size gets pretty large quickly. Nothing extraordinary, but I wanted to post these results together with a notebook on a github repository, which has a 100 MB cutoff. My MPS was exceeding that cutoff, by simply taking out the AL tensors and storing those I was saved (pun intended).

**Comment by huangrzh** [comment]
@Jutho @maartenvd Yes, my question is saving a vector of Dicts (converted from TensorMap) into a single file. I open this issue because it can be very inconvenient in practical calculations when one has many TensorMap objects and save each TensorMap into independent files. I can't find a simple way or a library to realize this. But as Jutho pointed out, a nested Dict can also realize what I want. I will try a nested Dict and see whether it's easy and convenient.

**Comment by maartenvd** [comment]
I really don't get it. Again - did you try jld2?

```
julia> using MPSKit,TensorKit,JLD2

julia> state = FiniteMPS(10,ℂ^2,ℂ^10);

julia> @save "test.jld" state

julia> state = nothing

julia> @load "test.jld"
1-element Vector{Symbol}:
 :state

julia> norm(state)
1.0

```

If you instead really want to work with vector of dictionaries, then you can even use BSON
```
julia> array_of_dicts = convert.(Dict,state.AL);

julia> @BSON.save "test.bson" array_of_dicts

julia> @JLD2.save "test.jld" array_of_dicts
```

I do see the point of having some saving functionality that only saves the bare minimum, I guess there it would make sense to add some conversions between array-of-dict to (in)finitemps

**Comment by huangrzh** [comment]
@maartenvd My applogies... I thought jld2 doesn't support saving a vector of dicts. Everything is good for me now. Thanks for the explanation. Since jld2 can be used to save a set of any tensors very conveniently, I think I can close this issue now.
