### ISSUE TITLE
`overwrite` argument doesn't work

### ISSUE THREAD

**Issue by Jutho** [maartenvd/MPSKit.jl#32]
On https://github.com/maartenvd/MPSKit.jl/blob/f86f5fcd265ca44efdd1d6b3343d486418d12ce6/src/states/finitemps.jl#L101 you probably want `copy.(site_tensors)` or `deepcopy(site_tensors)`.

**Comment by maartenvd** [comment]
aha I think the fix is even simpler

`site_tensors = overwrite ? site_tensors : copy(site_tensors); `

**Comment by Jutho** [comment]
Ah indeed, the two branches got reversed.

**Comment by maartenvd** [comment]
I used to do this because I didn't know that leftorth! also has to allocate a new vector for its output.
