### ISSUE TITLE
Quasiparticle types not exported

### ISSUE THREAD

**Issue by HumpyBlumpy** [maartenvd/MPSKit.jl#36]
Hi,
Thanks for this great package!

I noticed that the quasiparticle (QP, InfiniteQP, FiniteQP) types are not exported. Can they be exported?
It would help in writing functions that accept such objects (obtained via the excitations function).

On that subject, may I ask what is the purpose of the "utility leg" of the B tensor in the quasiparticle state? 
I find myself having to manually remove it (and since I could not find an easy way to accomplish it with TensorKit, I just convert it to an array and build a new TensorMap without the useless index).

**Comment by maartenvd** [comment]
Hi,

it's great that you're succesfully using this package!

I have pushed a bunch of recent commits, the quasiparticle types should now be exported :) I originally wanted to hide those types, as I'm not very happy with their design and find them a bit clunky to use.

The utility leg is important for symmetric tensors. If you have an SU_2 symmetric groundstate, then quasiparticle states without utility leg will live in the same symmetry sector as the groundstate. That is not what you want, the physical excitations typically live in different sectors, and these can be targeted by giving the excitation tensor an extra leg with a non-trivial charge. 

That is also why generically, they cannot be removed. I'm guessing you're using non-symmetric tensors, in which case you can probably remove them by:

```
julia> qp = MPSKit.LeftGaugedQP(rand,ts);

julia> typeof(qp[1])
TensorMap{ComplexSpace, 2, 2, Trivial, Matrix{ComplexF64}, Nothing, Nothing}

julia> remove_utility_leg(t) = t * isomorphism(domain(t),space(t,4)');

julia> typeof(remove_utility_leg(qp[1]))
TensorMap{ComplexSpace, 2, 1, Trivial, Matrix{ComplexF64}, Nothing, Nothing}

```

Note that this may throw errors when using a symmetric tensor network (the state here is su2 symmetric):

```
julia> qp = LeftGaugedQP(rand,ts,sector=SU₂(0)); 

julia> remove_utility_leg(qp[1]); # this works, the charge 0 sector leg can be removed

julia> qp = LeftGaugedQP(rand,ts,sector=SU₂(1));

julia> remove_utility_leg(qp[1]); # impossible, the leg carries a charge
ERROR: SpaceMismatch(codomain (Rep[SU₂](1=>1)' ⊗ Rep[SU₂](1/2=>5, 3/2=>3)) and domain ProductSpace(Rep[SU₂](1/2=>5, 3/2=>3)) are not isomorphic)
Stacktrace:
 [1] isomorphism(#unused#::Type{Matrix{Float64}}, cod::ProductSpace{GradedSpace{SU2Irrep, TensorKit.SortedVectorDict{SU2Irrep, Int64}}, 2}, dom::ProductSpace{GradedSpace{SU2Irrep, TensorKit.SortedVectorDict{SU2Irrep, Int64}}, 1})
   @ TensorKit ~/TensorKit.jl/src/tensors/linalg.jl:80
 [2] isomorphism
   @ ~/TensorKit.jl/src/tensors/linalg.jl:77 [inlined]
 [3] isomorphism
   @ ~/TensorKit.jl/src/tensors/linalg.jl:73 [inlined]
 [4] remove_utility_leg(t::TensorMap{GradedSpace{SU2Irrep, TensorKit.SortedVectorDict{SU2Irrep, Int64}}, 2, 2, SU2Irrep, TensorKit.SortedVectorDict{SU2Irrep, Matrix{ComplexF64}}, FusionTree{SU2Irrep, 2, 0, 1, Nothing}, FusionTree{SU2Irrep, 2, 0, 1, Nothing}})
   @ Main ./REPL[3]:1
 [5] top-level scope
   @ REPL[7]:1

```

**Comment by HumpyBlumpy** [comment]
Yes I am not using any symmetries.
Thanks for adding the QP types and for the detailed explanation!
