### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by HumpyBlumpy** [maartenvd/MPSKit.jl#37]
Hi, 
I noticed that when running memory intensive computations, Julia eats up all available RAM and does not free it up, even though it is not assigned to any variables in scope.
This sometimes leads to julia crashing. When running on a HPC cluster, my job often gets killed because it exceeds the memory given ( I request 16 GB per core).

For example, running excitation for 200 values of momenta allocates around 60GB of ram. Sometimes it crashes during this, sometimes after (during time evolution). Also had it crash at the very end of a simulation when making a plot.

I dont think there is any problem with this package, but I am wondering if you have any tips of how to deal with this.
I am new to Julia, but it seems that this issue should be quite common in these tensor networks calculations, unless I am doing something terribly wrong.
I tried playing with GC.gc() (for example, trying to free up the RAM taken by the excitation calculation) but it does not reduce it.
While I could request more RAM on the cluster, I dont see how it will help, since it seems that julia will gladly use it all!

**Comment by Jutho** [comment]
Adding these two lines:
```
using TensorOperations
TensorOperations.disable_cache()
```
will probably help. You can read more about this here: 
https://jutho.github.io/TensorOperations.jl/stable/cache/

**Comment by maartenvd** [comment]
On master there should now be a parallel = true/false switch for excitations, but if this and the TensorOperations cache don't help,  it may be useful to share a minimal example for your use-case

**Comment by Jutho** [comment]
It's probably also useful to know how the cluster communicates to the process (Julia in this case) how much memory it can use? Or is it just the end user who is responsible to ensure that the program does not exceed the requested amount, without the operating system telling the application in any way about this maximum?

**Comment by HumpyBlumpy** [comment]
Thanks for the quick suggestions!

I tried disabling the cache on my local machine and it seems to have made a huge difference!
Running the same script with excitation now still left me with ~8GB of free memory, whereas previously it would completely fill up my 16GB. 
I am wondering now whether it would make sense to have the cache on for parts of the simulation and off for others?
For example, turning it off for the excitation calculation but turning it back on for time evolution? or maybe doing time evolution for a long time would also fill up the cache?

Regarding the cluster, ours uses SLURM, and I was specifying the memory via `#SBATCH --mem-per-cpu=16000`. However, I just checked and it seems that it does not actually communicate this to julia (printing `Sys.total_memory()` returns 128GB).
So I guess this is a problem since the cache size is 0.25*128GB (I am guessing that the documentation in https://jutho.github.io/TensorOperations.jl/stable/cache/#TensorOperations.enable_cache is not up to date)

I am only using a single CPU core on the cluster, so I am assuming the parallel or not keyword should not change anything.

Thanks again!

**Comment by HumpyBlumpy** [comment]
Ok so I tried reenable the cache on my local pc, before calling timestep!. The julia session crashed with some seg fault error.

Judging by memory usage, it definitely seems that the cache is getting full. If I am reading https://github.com/Jutho/TensorOperations.jl correctly, once it is full, it actually deteriorate performance, so I guess the solution is to disable it altogether.

**Comment by maartenvd** [comment]
You can also set the maximum cache size yourself

**Comment by Jutho** [comment]
The seg fault should definitely not happen.

**Comment by HumpyBlumpy** [comment]
The seg fault appeared to be something due to multi threads. It disappeared when I switched to a single thread. 
In any case, I think disabling the cache solves the memory issue and I did not notice any slow down (in fact I think it is a bit faster without the cache)
Thanks for the help!
