### ISSUE TITLE
Gauge conversion of topological QP

### ISSUE THREAD

**Issue by HumpyBlumpy** [maartenvd/MPSKit.jl#38]
Hi,

I think there might be a problem with the gauge conversion of the quasiparticle type, when the left and right ground states are different. 
The resulting B tensor does not satisfy the right gauge-fixing condition.

Here is a minimal example:

```
using MPSKit,MPSKitModels
using TensorKit


########### helper functions to find symmetry broken ground states
function get_bond_dimensions(state::Union{FiniteMPS,InfiniteMPS,MPSComoving}) 
    N=length(state)+1
    bonds = Array{Int}(undef,N)
    for i in 1:N
        bonds[i] = dim(left_virtualspace(state,i-1))
    end
    return bonds
end

get_max_bond_dim(state::Union{FiniteMPS,InfiniteMPS,MPSComoving}) = maximum(get_bond_dimensions(state))

function VUMPS_with_init_state(init_gs_guess::InfiniteMPS,ham::MPOHamiltonian,max_bond_dim::Int;maxiter::Int = 400)
    function my_finalize(iter,state,ham,envs)
        if get_max_bond_dim(state) < max_bond_dim::Int
            state,envs = changebonds(state,ham,VUMPSSvdCut(trscheme = truncdim(max_bond_dim)),envs)
        end
        return state,envs;
    end
    return find_groundstate(init_gs_guess,ham,VUMPS(maxiter=maxiter,finalize=my_finalize));
end 
###########

ham = nonsym_ising_ham(J=-1.0,lambda = 0.5,spin=1//2)

sx,sy,sz  =nonsym_spintensors(1//2)

up = zeros(ComplexF64,1,2,1);
up[:,1,:] .= 1.0
up_data = TensorMap(up,ℂ^1 ⊗ ℂ^2,ℂ^1);
dn = zeros(ComplexF64,1,2,1);
dn[:,2,:] .= 1.0
dn_data = TensorMap(dn,ℂ^1 ⊗ ℂ^2,ℂ^1);
up_state = InfiniteMPS([up_data]);
dn_state = InfiniteMPS([dn_data]);

# find the two symmetry broken ground states
gs⁺,_ = VUMPS_with_init_state(up_state,ham,10);
gs⁻,_ = VUMPS_with_init_state(dn_state,ham,10);

# check
@info expectation_value(gs⁺,sz)
@info expectation_value(gs⁻,sz)

# find kink excitation
k = 0.2;
#(triv_energies,triv_Bs) = excitations(ham,QuasiparticleAnsatz(),k,gs⁺,num=1);
(top_energies_pm,top_Bs_pm) = excitations(ham,QuasiparticleAnsatz(),k,gs⁺,environments(gs⁺,ham),gs⁻,environments(gs⁻,ham),num=1);


qp_state = top_Bs_pm[1];
qp_stateR = convert(RightGaugedQP,top_Bs_pm[1]);


B = qp_state[1];
BR = qp_stateR[1];

AL = qp_state.left_gs.AL[1]
AR = qp_stateR.right_gs.AR[1]

@tensor LGzero[k l; m] := B[i j; k l]*conj(AL[i j;m]);

@info norm(LGzero) # 2.8262689435084304e-16


@tensor RGzero[k l; t] := BR[l j; k m]*conj(AR[t j;m]);

@info norm(RGzero) #0.24027386103287698
```

**Comment by maartenvd** [comment]
Hi ,

great that you're able to use this bit of code! Regarding your question - the rightgauge I used to pick was to impose the condition on the AR from the left groundstate. It's nicer/more consistent to use the right AR for the rightgauge and the left AL for the leftgauge, so I changed the code (and your example now works)

A very small note - one should be careful in finding the different groundstates by using two different initial states and then calling vumps. Vumps is rather eager in destroying your initial state, and for more complicated models it is quite possible that you might find the same groundstate twice. I typically find a single groundstate, and then use the symmetry transformation that maps one groundstate into the other to construct the other vacuum.

Also - there's still a bit of a discussion on how to uniquely determine the energy of such domainwall states (there is an ambiguity when you have two groundstates with different per-site-energy-density). I'm not sure if that's important for your research, but I'd always check both the + - kink and the - + kink

**Comment by HumpyBlumpy** [comment]
Thanks @maartenvd for the quick fix and suggestions!
I agree finding the different ground states via the symmetry transformation is a good idea.
For your second point, are you saying that +-,-+ kinks could have different energies?
Is there a simple way of converting a kink to its antikink with the package?

**Comment by HumpyBlumpy** [comment]
I think this works:
```
function flip_kink(qp_state::LeftGaugedQP,symm_op)
    left_gs = qp_state.right_gs
    right_gs = qp_state.left_gs
    VL = qp_state.VLs[1]
    @tensor VL2[-1;-3 -2] := adjoint(VL)[-1;-3 1]*symm_op[1;-2];
    qp_state_flipped = LeftGaugedQP(left_gs,right_gs,[VL2'],qp_state.Xs,qp_state.momentum)
end

```

**Comment by maartenvd** [comment]
> For your second point, are you saying that +-,-+ kinks could have different energies?

yes, there's an issue specifically for systems where the energy density is not uniform (larger unit cells). We can only really define energies with respect to another state, and if the left energy density is [e1,e2] while the right energy density is [e2,e1], then it is not completely clear how one should define the kink's energy. This is very rarely an issue, but I have run into it.
