### ISSUE TITLE
tol argument in TDVP exponentiate 

### ISSUE THREAD

**Issue by HumpyBlumpy** [maartenvd/MPSKit.jl#40]
This is a follow up on https://github.com/maartenvd/MPSKit.jl/issues/39#issuecomment-1178868597_ but I thought warranted a separate thread.

Changing tolgauge in TDVP, which sets tol in Lancos does not seem to have any effect. 
Per the discussion in https://github.com/Jutho/KrylovKit.jl/issues/52#issue-1169776687, changing eager to true leads to the expected behavior.

**Comment by maartenvd** [comment]
I have exposed the exponentiation algorithms in the TDVP(2) structs, so both eager and tol can now be manually set and played with

**Comment by maartenvd** [comment]
out of curiosity, can you also let me know if (or how) you end up getting satisfactory performance? I can tweak the defaults a bit, or investigate why something is unreasonably slow :)

**Comment by HumpyBlumpy** [comment]
@maartenvd yes! setting eager=true makes a pretty dramatic difference. I also set tol=1e-5 which is closer to dt^2 per your suggestion. Gives me about a factor of 10 decrease in the total time of the simulations.
