### ISSUE TITLE
entropy may sometimes return NaN

### ISSUE THREAD

**Issue by HumpyBlumpy** [maartenvd/MPSKit.jl#43]
The current entropy function sometimes fails by returning NaN. This occurs for example after using changebonds to increase the bond dimension of a state.
Perhaps it is better to use something like this?

```
function entropy(state::Union{FiniteMPS,MPSComoving,InfiniteMPS},n::Int=0)
    pv = entanglement_spectrum(state,n).^2 .+ 1e-20
    -sum(log.(pv) .* pv)
end
```

**Comment by Jutho** [comment]
I guess the error comes only from entanglement values which are exactly zero.
Maybe it's better to define a more robust function to compute `x*log(x)` that deals with `x=0` properly, and use this in the definition.
