### ISSUE TITLE
Issue with recreating InfiniteMPS after expanding bond dimension

### ISSUE THREAD

**Issue by HumpyBlumpy** [maartenvd/MPSKit.jl#46]
Hello,

I encountered a strange behavior after expanding the bond dimension of an InfiniteMPS, followed by making a new InfiniteMPS using one of its tensors. I think there is something wrong with the newly created InfiniteMPS, although most operations work properly (and return same results as the original MPS), calling environments fails to converge.

I was not able to pinpoint what goes wrong exactly, but here is a minimal example:
```
using MPSKit,MPSKitModels,TensorKit

bondim=10

ham = nonsym_ising_ham(J=-1.0,lambda = 0.45,spin=1//2)

gs_init = InfiniteMPS([ℂ^2],[ℂ^bondim]);

(gs,_,_) = find_groundstate(gs_init,ham,VUMPS(maxiter=400));


extra_bonds = bondim
gs_expanded,_ = changebonds(gs,ham,OptimalExpand(trscheme=truncdim(extra_bonds)))

gs_2 = InfiniteMPS(gs.AL);
gs_3 = InfiniteMPS(gs_expanded.AL); #similar if using AR, AC

environments(gs_2,ham); #works ok

environments(gs_3,ham); #calcrw failed to converge 0.16636273007464153
```

Thanks!

**Comment by HumpyBlumpy** [comment]
Hi Maarten,

Thanks for the explanation.

I am doing time evolution of a MPSComoving, which is time consuming and so I want to save snapshots of the state for later analysis. To save on diskspace, I figured that I only need to save some of the tensors (e.g ALs), and I found this nice feature of JLD2 "custom serialization" which allows to nicely implement this (see https://gist.github.com/HumpyBlumpy/fdbd43691546cf351fa99fb42968be51).
When loading the state, it calls the constructor with only the AL tensor, which causes the issue similar to my example.

I suppose one solution for me would be to not use the custom serialization for InfiniteMPS, i.e save all the tensors of the InfiniteMPS. The extra diskspace cost should be negligible compared to the large window. Does the issue with non-injectivity you describe occur also for FiniteMPS? 
I construct my initial MPSComoving by hand using ground state and excitation tensors of bond dimension D. Most of the window has bond dimension of 2D, except of few places where it is D. I want to have a uniform bond dimension so prior to doing the time evolution I expand the ground state from D to 2D using changebonds, manually pad the "edge tensors" between the window and the ground states with extra zeros, and then call changebonds on the full MPSComoving to increase any "bulk" tensor of dimension less than 2D.

Thanks,
Ron

**Comment by maartenvd** [comment]
Hi Ron,

indeed, the easiest solution would probably be to save all tensors for an InfiniteMPS - there are no such problems for finite matrix product states. Only infinite repetitions of the non-injective AR tensor are mathematically problematic.

As an aside, I think the serialization code from the gist is not guaranteed to work. For example, if you take a finite mps and update the C tensor at position i, then the finite mps structure will only have non-missing ALs for all sites before position i and non-missing ARs for all sites after position i. All other ALs/ARs will be set to missing. Only saving the ALs will then not be enough to reconstruct the state.

I was rather vague about this in the documentation, I hoped to hide all of this behind the "smart" getters "state.AL/AR/AC", and not have to expose anyone to the inner workings of finite states. For example, if you take your code and replace line 27 with " FiniteMPSSerialization(a.AL[1:end-1],a.AC[end])" (note ALs => AL, ACs => AC), then everything will/should work just fine. The fields in finitempsserialization can then also be changed from Union{A,missing} to A.

In any case I'm happy that you're successfully using mpscomoving!

Maarten

**Comment by HumpyBlumpy** [comment]
Thanks!, I removed the serialization of the InfiniteMPS and it seems to work.

Thanks also for pointing out the AL->ALs difference, I have not appreciated it enough before!
