### ISSUE TITLE
Nonuniform Hamiltonian

### ISSUE THREAD

**Issue by HumpyBlumpy** [maartenvd/MPSKit.jl#48]
Hi,

Is it possible to create and use a non uniform Hamiltonian?

**Comment by maartenvd** [comment]
Yes, but it's not very nice (as it was originally not really supported). I assume you mean the combination of an mpscomoving with a non-uniform hamiltonian, where a uniform hamiltonian is used for the left/right groundstate?

You can construct a non-uniform hamiltonian and initialize the mpscomoving environments with as bulk operator this non-uniform hamiltonian and with as left/right environments at the edges the uniform left_gs/right_gs environments. I will add an example file that does this in the coming days :)

**Comment by HumpyBlumpy** [comment]
Yes exactly. I want to have a spatially dependent Hamiltonian inside the window and uniform outside (the same on both sides in my case). 
I thought this would be relatively straightforward, basically a combination of finite TDVP with the infinite TDVP (I should have probably mentioned that I am interested in TDVP time evolution)
Looking forward to your example!

**Comment by HumpyBlumpy** [comment]
Hi @maartenvd, just wondering if you had a chance to add the example file.
Something very simple just illustrating how to make the hamiltonian and TDVP work should suffice :)

**Comment by maartenvd** [comment]
Ah right, I completely forgot about this:

```
using MPSKit, MPSKitModels, TensorKit, Plots;
th = nonsym_ising_ham(lambda=2);
ts = InfiniteMPS([ℂ^2],[ℂ^10]);

(ts,envs) = find_groundstate(ts,th,VUMPS());

non_uniform = repeat(th,10);
non_uniform[5][1,3] = -th[1][1,3]; # flip the magnetic field in the middle

window = MPSComoving(ts,10);

# create the environments with the non-uniform hamiltonian, but at the edges we use the uniform-hamiltonian-environments
window_envs = environments(window,non_uniform,leftenv(envs,1,ts),rightenv(envs,10,ts)); 


(window,window_envs) = find_groundstate(window,non_uniform,DMRG(),window_envs);

(sx,sy,sz) = nonsym_spintensors(1//2);
plot(real.(expectation_value(window,sx)))
```

**Comment by maartenvd** [comment]
So the idea is to construct window_environments with the non-uniform hamiltonian, but manually pass in the environments of the uniform hamiltonian.

**Comment by HumpyBlumpy** [comment]
Thanks, works great!
This is actually pretty elegant! :)
