### ISSUE TITLE
Unable to construct a `FiniteMPS` that has alternating virtual spaces without specifying all virtual spaces.

### ISSUE THREAD

**Issue by DaanMaertens** [maartenvd/MPSKit.jl#93]
A possible constructor for a `FiniteMPS` is to specify a (vector of) physical spaces and a single `maxvirtspace` representing the maximum space one wants on the virtual level, according to
```julia
FiniteMPS(rand, ComplexF64, rand(3:2:20) ,pspace, maxvirtspace)
```
If one however wants the physical space `pspace=Rep[SU₂](1//2 => 1)` then this constructor will fail because it will try to find the infimum between a space containing integer reps of SU2 and another containing half-integers only. The virtual spaces of the mps should be alternating between integer and half-integer and this can currently only be done by using the constructor that requires all the virtual spaces.

**Comment by DaanMaertens** [comment]
see commit [cad1d97](https://github.com/maartenvd/MPSKit.jl/commit/cad1d9705825c6b6f0972afe223d6b41a6db80b4) for my proposed solution.

**Comment by Jutho** [comment]
What happens if you make `maxvirtspace` have both integer and halfinteger representations?

**Comment by Jutho** [comment]
I agree that being able to specify a vector of `maxvirtspace`s should be an option.

The simplicity of specifying a single space is of course attractive, and I think it works generally, but indeed, you need to think through the consequences and how to choose/construct it.

**Comment by Gertian** [comment]
You could also assume that the user defines the maximum dimension of the virtual Hilbert space.
So if you give it ```maxvirtdim = 5``` with e.g. SU(2) sectors it might take two spin 1/2 sectors and a spin 0 sector. Or 5 spin 0 sectors etc...

Something like this could be easily achieved by using the truncdim option in TensorKit.svd()  .

**Comment by lkdvos** [comment]
```julia
# constructor with a single physical space, and a single virtual space.
FiniteMPS([f, elt], pspace::VectorSpace, maxvspace::ElementarySpace; length=N, kwargs...)
# constructor with variable physical spaces and variable virtual spaces
FiniteMPS([f, elt], pspaces::Vector{<:VectorSpace}, maxvspaces::Vector{<:ElementarySpace}; kwargs...)
```

While it might be convenient to automatically infer all other combinations, it might also become quite a mess to keep this implemented nicely, and I would argue that the it is not that much more verbose to type `repeat(alternatingspaces, N/2)`.
In the case where you explicitly wish to construct an MPS which is not full-rank, probably it is better to really require the user to construct the tensors themselves, as it is also less obvious how to gauge them consistently I think.

**Comment by Gertian** [comment]
Since it's a finiteMPS I'd just build the n-th virtual space as (physical space)^n or a trunctated version thereof. 
But indeed it's slightly ill defined since the truncated sectors would be randomly picked. 

Perhaps something like : ```FiniteMPS([f, elt], pspaces::Vector{<:VectorSpace}, truncator; kwargs...)''' with truncator an algorithm that is passed to the QR/SVD used in the constructor ? Like this users can freely choose between the available truncation methods from TensorKit.

**Comment by lkdvos** [comment]
But again, it really does not make sense to truncate a just-initialized state, no matter what truncated algorithm you are using? For example, I could ask for a state filled with zeros, in which case any truncation method fails anyways. If you really want to truncate an MPS, I think it makes more sense to construct it, and then just truncate the result.
The FiniteMPS constructor does not really need to have the responsability of also truncating.
